ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.0
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
    - id: black
      args: [--skip-string-normalization]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests

- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.2
  hooks:
    - id: gitleaks
